apiVersion: v1
kind: Service
metadata:
  name: siae-media
  namespace: siae
  labels:
    app: siae-media
  annotations:
    # Prometheus 服务发现注解
    prometheus.io/scrape: "true"
    prometheus.io/port: "8084"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app: siae-media
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
  sessionAffinity: None
